meta_name: "Jamfinder"
meta_title: "Jamfinder | Play different. Play together"
meta_description: "Jamfinder brings musicians together by genres, instruments, and locations"
meta_image: "https://res.cloudinary.com/drxcsc3ye/image/upload/v1693838639/purple_background_brand.png"
